#define MAGIC_NUMBER 'k'

#define SET_BAUDRATE _IOWR(MAGIC_NUMBER ,1,int)

#define SET_NON_STOP_BITS  _IOWR(MAGIC_NUMBER ,2,int)
#define SET_DIRECTION_WRITE  _IOW(MAGIC_NUMBER ,3,int)
#define DEFAULT_DATA _IOWR(MAGIC_NUMBER ,4,int)

